# Server configuration
port: 3000

# Dehydrated base directory (where certificates and data are stored)
dehydratedBaseDir: /Volumes/Data/jan.schumann/acme
dehydratedConfigFile: config

# Enable file watcher for automatic reloading
enableWatcher: false

# Logging configuration
logging:
  level: debug
  encoding: console
  outputPath: ""
