port: 3000
dehydratedBaseDir: ./data
enableWatcher: true
logging:
  level: debug
  encoding: console
  outputPath: ""
plugins:
  example:
    enabled: true
    path: ./examples/plugins/simple/simple
    config:
      name: example
  openssl:
    enabled: true
    path: /Users/jan.schumann/Development/Projects/schumann-it/dehydrated-api-metadata-plugin-openssl/openssl
    config: {}
