# Server configuration
port: 3000

# Dehydrated base directory (where certificates and data are stored)
dehydratedBaseDir: ./data

# Enable file watcher for automatic reloading
enableWatcher: false

# Logging configuration
logging:
  level: debug
  encoding: console
  outputPath: ""
