# Server configuration
port: 3000

# Dehydrated base directory (where certificates and data are stored)
dehydratedBaseDir: ./data
dehydratedConfigFile: config

# Enable file watcher for automatic reloading
enableWatcher: false

# Logging configuration
logging:
  level: debug
  encoding: console
  outputPath: ""

#plugins:
#  simple:
#    enabled: true
#    registry:
#      type: local
#      config:
#        path: "./examples/plugins/simple/simple"
#    config:
#      name: "Simple Plugin"